### ISSUE TITLE
sensu-go-check failed to run

### ISSUE THREAD

**Issue by maximnik** [jaredledvina/sensu-go-ansible#97]
I try to use sensu-go-check module

1. Added module path to library path:
`cat /etc/ansible/ansible.cfg
library = /usr/lib/python2.7/site-packages/ansible/modules:/etc/ansible/playbooks/sensu-go-ansible/library`

2. Create yml file with check definition
```
---
- hosts: all
  tasks:
    - name: Create a new check
      sensu_go_check:
        state: present
        host: <hostname>
        protocol: https
        port: 8081
        password: <password>
        namespace: default
        subscriptions:
          - default
        name: check_root_disk
        command: /usr/lib64/nagios/plugins/check_disk -w 15 -c 10 -p "/"
        interval: 60
        validate_certs: no
```

3. run ansible
`ansible-playbook -i hosts checks.yml`

4. get error
```
TASK [Create a new check] ***********************************************************************************************************************************
fatal: [172.22.155.230]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 172.22.155.230 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/maximni/.ansible/tmp/ansible-tmp-1558048408.29-233429134634977/AnsiballZ_sensu_go_check.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/maximni/.ansible/tmp/ansible-tmp-1558048408.29-233429134634977/AnsiballZ_sensu_go_check.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/maximni/.ansible/tmp/ansible-tmp-1558048408.29-233429134634977/AnsiballZ_sensu_go_check.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_sensu_go_check_payload_jzafha/__main__.py\", line 489, in <module>\r\n  File \"/tmp/ansible_sensu_go_check_payload_jzafha/__main__.py\", line 485, in main\r\n  File \"/tmp/ansible_sensu_go_check_payload_jzafha/__main__.py\", line 444, in run_module\r\n  File \"/tmp/ansible_sensu_go_check_payload_jzafha/__main__.py\", line 322, in auth\r\nTypeError: 'NoneType' object has no attribute '__getitem__'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
